
FROM eclipse-temurin:17-jdk-alpine

WORKDIR /app

COPY target/tu-proyecto.jar /app/tu-proyecto.jar


EXPOSE 8080


ENV SPRING_PROFILES_ACTIVE=prod


ENTRYPOINT ["java", "-jar", "/app/tu-proyecto.jar"]
